name: pytest

on:
  push:
    branches: [master, main, test-*]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres:17.2
        # Provide the password for postgres
        env:
          POSTGRES_USER: webapp
          POSTGRES_DB: webapp
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Python dependencies
      shell: bash
      run: pip install -e .[dev,test]

    - name: Run tests
      shell: bash
      run: python -m pytest test
      env:
        POSTGRES_HOSTNAME: localhost
