name: pytest

on:
  push:
    branches: [master, main, test-*]

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres:17.2
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: webapp
          POSTGRES_USER: webapp
          POSTGRES_DB: webapp
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Python dependencies
      shell: bash
      run: pip install -e .[dev,test]
